#!/usr/bin/env python3
"""build_tour_package.py — recombine a camera-only tour KML with the CANONICAL geometry.

The tour library (docs/tours/*.kml) is camera-only (gx:FlyTo paths, no polygons); the buildings
in a recorded video come from whatever geometry file was loaded in Google Earth at record time.
Old videos therefore show old skylines. This script makes regeneration deterministic: it splices
a tour's <gx:Tour> element into the canonical geometry document and emits ONE self-contained
package KML — open it in Google Earth Pro, press play, re-record. Geometry provenance (source
file + sha + placemark count) is stamped into the package description so a video can always be
traced to the skyline it showed.

CANONICAL GEOMETRY: docs/geometry.kml (the hand-edited footprints; verified 2026-07-03 identical
to kml_versions/Geometry/Geometry-2026-05-18-labeled.kml). Hand-edits continue to land there;
packages are DERIVED — never hand-edit a package.

Usage:
  python scripts/build_tour_package.py docs/tours/205sec.kml            # one tour
  python scripts/build_tour_package.py --all                            # every camera-only tour
Output: docs/tours/packages/<tour-stem>__<geometry-date>.kml
"""
import hashlib
import pathlib
import re
import sys
from xml.dom import minidom

ROOT = pathlib.Path(__file__).resolve().parent.parent
GEOMETRY = ROOT / "docs" / "geometry.kml"
OUTDIR = ROOT / "docs" / "tours" / "packages"
GX_NS = 'xmlns:gx="http://www.google.com/kml/ext/2.2"'


def extract_tour(tour_path: pathlib.Path) -> str:
    x = tour_path.read_text(encoding="utf-8", errors="replace")
    m = re.search(r"<gx:Tour\b.*?</gx:Tour>", x, re.S)
    if not m:
        raise SystemExit(f"{tour_path}: no <gx:Tour> element (not a camera tour)")
    return m.group(0)


def build(tour_path: pathlib.Path) -> pathlib.Path:
    geom = GEOMETRY.read_text(encoding="utf-8", errors="replace")
    tour = extract_tour(tour_path)
    sha = hashlib.sha256(GEOMETRY.read_bytes()).hexdigest()[:12]
    n_pm = len(re.findall(r"<Placemark", geom))

    out = geom
    # ensure the gx namespace exists on the root <kml> tag
    kml_tag = re.search(r"<kml\b[^>]*>", out).group(0)
    if "xmlns:gx" not in kml_tag:
        out = out.replace(kml_tag, kml_tag[:-1] + f" {GX_NS}>", 1)
    # provenance stamp + the tour, injected right after the <Document> opening tag
    doc_tag = re.search(r"<Document\b[^>]*>", out)
    if not doc_tag:
        raise SystemExit(f"{GEOMETRY}: no <Document> element")
    stamp = (f"\n<!-- TOUR PACKAGE (generated by scripts/build_tour_package.py — do not hand-edit)"
             f"\n     tour:     {tour_path.relative_to(ROOT)}"
             f"\n     geometry: {GEOMETRY.relative_to(ROOT)} sha256:{sha} placemarks:{n_pm} -->\n")
    out = out.replace(doc_tag.group(0), doc_tag.group(0) + stamp + tour, 1)

    minidom.parseString(out)  # well-formedness gate — refuse to emit broken XML
    OUTDIR.mkdir(parents=True, exist_ok=True)
    dest = OUTDIR / f"{tour_path.stem}__geom-{sha}.kml"
    dest.write_text(out, encoding="utf-8")
    return dest


def camera_only_tours():
    for fp in sorted((ROOT / "docs" / "tours").rglob("*.kml")):
        if "packages" in fp.parts:
            continue
        x = fp.read_text(encoding="utf-8", errors="replace")
        if "<gx:Tour" in x and "<Polygon" not in x:
            yield fp


if __name__ == "__main__":
    args = sys.argv[1:]
    targets = list(camera_only_tours()) if args == ["--all"] else [pathlib.Path(a) for a in args]
    if not targets:
        raise SystemExit("usage: build_tour_package.py <tour.kml> [...] | --all")
    for t in targets:
        dest = build(t)
        print(f"packaged: {dest.relative_to(ROOT)}")
