#!/usr/bin/env python3
"""build_nav.py — single source of truth for curriculum prev|next navigation.

Stamps an idempotent nav markdown cell at the TOP (right after the title /
"### Running the cells" block) and at the BOTTOM (end) of each curriculum
notebook, linking the previous and next notebook in the reading sequence.

Nav cells are marked two ways so a re-run REPLACES them rather than appending
duplicates: a stable cell id (``nav-top`` / ``nav-bottom``), cell metadata
``{"nav_cell": "top"|"bottom"}``, and an HTML-comment SENTINEL in the source.
Running the script twice produces a byte-identical notebook — that is what makes
future reorders of ORDER safe.

Touches ONLY nav cells; every code cell and every non-nav markdown cell is left
exactly as nbformat round-trips it (verified by the caller).

Usage:
    python scripts/build_nav.py                 # all notebooks in ORDER
    python scripts/build_nav.py JN0a_why_data   # one notebook (by stem)
    python scripts/build_nav.py --dir DIR ...   # target DIR instead of the canonical dir
"""
import sys
import os
import nbformat

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_DIR = os.path.normpath(os.path.join(HERE, "..", "notebooks", "curriculum"))

COURSE_PAGE = "https://berkeleybuild.com/data-science-curriculum.html"
COLAB_TMPL = ("https://colab.research.google.com/github/blockXblock/"
              "berkeley-housing-analysis/blob/main/notebooks/curriculum/{stem}.ipynb")
SENTINEL = "<!-- NAV:auto-generated by scripts/build_nav.py — do not edit by hand -->"

# THE reading sequence — the one ordered list. Reorder here and re-run to re-stamp all.
ORDER = [
    "JN0a_why_data", "JN0b_notebook", "JN0c_function", "JN0d_dataframe",
    "JN0e_charts", "JN0f_tools", "JN0g_agents", "JN0h_instruction_file",
    "JN1_ingest", "JN2_address_key", "JN3_spine_units", "JN4_events_stage",
    "JN5_year_cycle", "JN6a_apr_oracle", "JN6b_join_score",
]

# Display titles shown in the nav links (concise; the H1s vary in separator/length).
TITLES = {
    "JN0a_why_data":         "JN0a · Why municipal data",
    "JN0b_notebook":         "JN0b · What a computational notebook is",
    "JN0c_function":         "JN0c · What a function is",
    "JN0d_dataframe":        "JN0d · What a pandas DataFrame is",
    "JN0e_charts":           "JN0e · One set of numbers, many pictures",
    "JN0f_tools":            "JN0f · The tools we use",
    "JN0g_agents":           "JN0g · Building with agents",
    "JN0h_instruction_file": "JN0h · The agent instruction file",
    "JN1_ingest":            "JN1 · Getting the data in the door",
    "JN2_address_key":       "JN2 · The address key",
    "JN3_spine_units":       "JN3 · Build the spine + units",
    "JN4_events_stage":      "JN4 · Dated milestones + completion stage",
    "JN5_year_cycle":        "JN5 · Year & cycle tagging",
    "JN6a_apr_oracle":       "JN6a · Interrogate the oracle + generate your APR",
    "JN6b_join_score":       "JN6b · Join, decompose, score",
}


def colab(stem):
    return COLAB_TMPL.format(stem=stem)


def nav_source(stem):
    """The markdown body for the nav cell of `stem` (same for top and bottom)."""
    i = ORDER.index(stem)
    prev = ORDER[i - 1] if i > 0 else None
    nxt = ORDER[i + 1] if i < len(ORDER) - 1 else None

    if prev:
        left = f"← Previous: [{TITLES[prev]}]({colab(prev)})"
    else:  # endpoint: first notebook -> back to the course page
        left = f"← [Back to the course]({COURSE_PAGE})"

    if nxt:
        right = f"Next: [{TITLES[nxt]}]({colab(nxt)}) →"
    else:  # endpoint: last notebook -> finished, back to the course page
        right = f"[🎉 You've finished the series — back to the course]({COURSE_PAGE})"

    return f"{SENTINEL}\n\n{left}  |  {right}"


def is_nav(cell):
    if cell.get("metadata", {}).get("nav_cell"):
        return True
    if cell.get("cell_type") == "markdown" and SENTINEL in "".join(cell.get("source", "")):
        return True
    return False


def make_nav_cell(stem, pos):
    cell = nbformat.v4.new_markdown_cell(source=nav_source(stem))
    cell["metadata"]["nav_cell"] = pos
    cell["id"] = "nav-top" if pos == "top" else "nav-bottom"   # stable -> idempotent
    return cell


def top_anchor(cells):
    """Index AFTER which the top nav goes: right after the '### Running the cells'
    cell if present, else right after the first (title) cell."""
    for i, c in enumerate(cells):
        if c.get("cell_type") == "markdown" and "### Running the cells" in "".join(c.get("source", "")):
            return i + 1
    return 1


def stamp(path, stem):
    nb = nbformat.read(path, as_version=4)
    # 1) strip any existing nav cells (idempotency: rebuild from stable anchors)
    nb.cells = [c for c in nb.cells if not is_nav(c)]
    # 2) insert top nav after the title/run-instruction block
    nb.cells.insert(top_anchor(nb.cells), make_nav_cell(stem, "top"))
    # 3) append bottom nav at the end
    nb.cells.append(make_nav_cell(stem, "bottom"))
    nbformat.write(nb, path)


def main(argv):
    target_dir = DEFAULT_DIR
    args = []
    i = 0
    while i < len(argv):
        if argv[i] == "--dir":
            target_dir = argv[i + 1]
            i += 2
        else:
            args.append(argv[i])
            i += 1
    stems = args if args else ORDER
    for stem in stems:
        if stem not in ORDER:
            raise SystemExit(f"unknown notebook stem: {stem!r} (not in ORDER)")
        path = os.path.join(target_dir, f"{stem}.ipynb")
        if not os.path.exists(path):
            raise SystemExit(f"not found: {path}")
        stamp(path, stem)
        print(f"stamped nav: {os.path.relpath(path)}")


if __name__ == "__main__":
    main(sys.argv[1:])
