#!/usr/bin/env python3
"""retime_tour.py — scale every leg of a tour, without touching the camera path.

WHY (John, 2026-08-26): Earth streams imagery and terrain tiles as the camera moves and renders
whatever has arrived, so a fast pass shows detail filling in late. Flying the same path more
slowly gives each tile longer to land. The corridor tours take --speed, but the hand-made ones
(the 200+ unit tour, the dramatic cuts) were not generated by gen_corridor_tour.py and have no
speed to set -- so scale their gx:duration values instead. Every waypoint keeps its exact
position, heading, tilt and altitude; only the time between them changes.

  python scripts/retime_tour.py kml/tours/foo.kml --factor 1.5 --out kml/tours/foo-slow.kml
"""
import argparse, os, re


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("tour")
    ap.add_argument("--factor", type=float, required=True, help=">1 slower, <1 faster")
    ap.add_argument("--out", required=True)
    ap.add_argument("--title-suffix", default="", help="appended to the tour name, e.g. ' (slow)'")
    a = ap.parse_args()
    x = open(a.tour, encoding="utf-8", errors="replace").read()

    before = sum(float(v) for v in re.findall(r"<gx:duration>([\d.]+)</gx:duration>", x))
    out = re.sub(r"<gx:duration>([\d.]+)</gx:duration>",
                 lambda m: f"<gx:duration>{float(m.group(1)) * a.factor:.2f}</gx:duration>", x)
    after = sum(float(v) for v in re.findall(r"<gx:duration>([\d.]+)</gx:duration>", out))
    if a.title_suffix:
        out = re.sub(r"<name>([^<]*)</name>",
                     lambda m: f"<name>{m.group(1)}{a.title_suffix}</name>", out, count=2)

    # THE CAMERA MUST BE UNTOUCHED -- assert it, do not assume it. Compare the whole document
    # with every duration blanked: anything else that differs is a bug. (An earlier version
    # matched <longitude>...</roll>, which broke on this very tour -- 211 Camera blocks but only
    # 210 <roll> tags, so the regex ran past the one camera without a roll into the next leg.)
    blank = lambda s: re.sub(r"<gx:duration>[\d.]+</gx:duration>", "<gx:duration/>", s)
    assert blank(x) == blank(out).replace(a.title_suffix, "") or blank(x) == blank(out), \
        "something other than the durations changed — refusing to write"
    os.makedirs(os.path.dirname(a.out) or ".", exist_ok=True)
    open(a.out, "w", encoding="utf-8").write(out)
    print(f"wrote {a.out}\n  {out.count('<gx:FlyTo>')} legs unchanged, "
          f"{before:.0f}s -> {after:.0f}s ({before/60:.1f} -> {after/60:.1f} min) at x{a.factor}")


if __name__ == "__main__":
    main()
