#!/usr/bin/env python3
"""site_meta.py — give every page an identity: description, Open Graph, favicon, canonical.

THE PROBLEM. Paste berkeleybuild.com into Slack, Bluesky, iMessage or a newsroom CMS and you
get a bare blue URL. Measured across all 15 pages: 0 Open Graph tags, 0 Twitter cards, 0 meta
descriptions, 0 favicons, and no <h1> on the homepage at all (sixteen <h3>s and nothing above
them). For a site whose whole purpose is to be cited by reporters and council members, the
link preview IS the first impression, and there wasn't one.

IT IS IDEMPOTENT. Everything it writes sits between two markers, so a re-run replaces the block
rather than stacking a second copy. Editing a page by hand between runs is safe; editing INSIDE
the markers is not, and the marker says so.

NO STATISTICS ON THE SOCIAL CARD -- deliberate. A shared card travels far past its context and
cannot be footnoted. The RHNA figure is coverage-limited and deliberately unpublished; a number
stamped into an image is exactly the kind of thing that gets quoted back without its caveat. So
the card carries the name, the promise, and the stage colours the flyovers use, and sends people
to the page for numbers that can be qualified.
"""
import os, pathlib, re, subprocess, sys

DOCS = pathlib.Path("docs")
SITE = "https://berkeleybuild.com"
NAME = "BerkeleyBuild"
BEGIN, END = "<!-- BEGIN site_meta (generated by scripts/site_meta.py — do not hand-edit) -->", "<!-- END site_meta -->"

# Editorial copy: a description is prose, not a derived figure, so it is written, not computed.
DESC = {
 "index.html": ("Berkeley's housing pipeline, from the city's own records",
   "An independent reconstruction of Berkeley's housing pipeline — entitlement to building "
   "permit to occupancy — built from primary sources and published in full."),
 "explorer.html": ("Pipeline Explorer",
   "Every tracked Berkeley housing project: dates, units, affordability, assessed value and "
   "RHNA cycle, searchable and sortable."),
 "explorer_v2.html": ("Pipeline Explorer",
   "Every tracked Berkeley housing project: dates, units, affordability and RHNA cycle."),
 "housing-audit.html": ("The Housing Audit",
   "Our count against the City's own submitted APR, row by row, with every difference named "
   "and sourced."),
 "pipeline-state.html": ("The Pipeline State",
   "Where every Berkeley housing project actually stands — filed, under review, entitled, "
   "permitted, building, or finished."),
 "players.html": ("The Players",
   "Who builds Berkeley: the developers, architects and owners behind the pipeline, drawn "
   "from permit and assessor records."),
 "methodology.html": ("Methodology",
   "How the record is built: the primary sources, the counting rules, and what we deliberately "
   "record as unknown."),
 "reporters.html": ("For Reporters",
   "Query Berkeley's housing record directly — the database, the documents, and the questions "
   "worth asking."),
 "reporters-local-models.html": ("Run the AI on your own computer",
   "A reporter's guide to querying the housing record with a local model, nothing leaving your "
   "machine."),
 "data-science-curriculum.html": ("Data Science Curriculum",
   "Rebuild Berkeley's housing record yourself, from the raw sources, across 19 notebooks."),
 "mayor-briefing-2026-07.html": ("More Homes, Healthy Corridors",
   "A data briefing for the Mayor on what Berkeley's own housing records show works."),
 "map.html": ("Housing Map", "Berkeley's tracked housing projects on a map."),
 "driving_survey_log.html": ("Driving Survey Log",
   "Field verification of the pipeline — what the buildings actually look like on the ground."),
 "possibility-lab-test.html": ("Possibility Lab Test",
   "A multi-city open-data APR experiment."),
 "technical-archive-2026.html": ("Technical Archive 2026",
   "Superseded technical project pages, kept for provenance."),
}

STAGES = [("#7a7a7a",), ("#b8860b",), ("#ff8000",), ("#00b8cc",), ("#2962ff",), ("#00a844",)]

FAVICON = '''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
<rect width="64" height="64" rx="12" fill="#1a365d"/>
<rect x="12" y="34" width="10" height="20" fill="#00a844"/>
<rect x="27" y="24" width="10" height="30" fill="#2962ff"/>
<rect x="42" y="14" width="10" height="40" fill="#ff8000"/>
</svg>
'''


def og_card(path):
    """1200x630 card: the wordmark, the promise, and the stage colours. No statistics."""
    from PIL import Image, ImageDraw, ImageFont
    W, H = 1200, 630
    img = Image.new("RGB", (W, H), "#1a365d")
    d = ImageDraw.Draw(img)
    for y in range(H):                                   # subtle vertical wash
        d.line([(0, y), (W, y)], fill=(26, 54 + y // 18, 93 + y // 9))

    def font(sz, bold=True):
        for p in ("/System/Library/Fonts/Supplemental/Arial Bold.ttf" if bold else
                  "/System/Library/Fonts/Supplemental/Arial.ttf",
                  "/System/Library/Fonts/Helvetica.ttc"):
            if os.path.exists(p):
                try:
                    return ImageFont.truetype(p, sz)
                except OSError:
                    pass
        return ImageFont.load_default()

    # the six stage colours, as a rule across the top — the same language as the flyovers
    x = 80
    for (c,) in STAGES:
        d.rectangle([x, 96, x + 128, 104], fill=c)
        x += 140
    d.text((80, 170), NAME, font=font(96), fill="#ffffff")
    d.text((80, 300), "Berkeley's housing pipeline,", font=font(52, False), fill="#cfe3ee")
    d.text((80, 366), "from the city's own records.", font=font(52, False), fill="#cfe3ee")
    d.text((80, 480), "entitlement  ·  building permit  ·  occupancy",
           font=font(34, False), fill="#8fb6d1")
    d.text((80, 536), "berkeleybuild.com", font=font(34), fill="#ffd166")
    img.save(path, "PNG", optimize=True)
    return path


def touch_icon(path, size=180):
    """The home-screen icon is SQUARE. Resizing the 1200x630 card into it squashes the
    wordmark; this redraws the favicon's three bars at icon scale instead."""
    from PIL import Image, ImageDraw
    img = Image.new("RGB", (size, size), "#1a365d")
    d = ImageDraw.Draw(img)
    u = size / 64.0
    for x, y, w, h, c in ((12, 34, 10, 20, "#00a844"), (27, 24, 10, 30, "#2962ff"),
                          (42, 14, 10, 40, "#ff8000")):
        d.rectangle([x * u, y * u, (x + w) * u, (y + h) * u], fill=c)
    img.save(path, "PNG", optimize=True)
    return path


def block(page):
    short, desc = DESC.get(page, (NAME, "Berkeley's housing pipeline, from the city's own records."))
    url = f"{SITE}/" if page == "index.html" else f"{SITE}/{page}"
    t = f"{short} — {NAME}" if page != "index.html" else f"{NAME} — Berkeley's housing pipeline"
    return "\n".join([
        BEGIN,
        f'<meta name="description" content="{desc}">',
        f'<link rel="canonical" href="{url}">',
        '<link rel="icon" type="image/svg+xml" href="/favicon.svg">',
        '<link rel="apple-touch-icon" href="/apple-touch-icon.png">',
        '<meta property="og:type" content="website">',
        f'<meta property="og:site_name" content="{NAME}">',
        f'<meta property="og:title" content="{t}">',
        f'<meta property="og:description" content="{desc}">',
        f'<meta property="og:url" content="{url}">',
        f'<meta property="og:image" content="{SITE}/og-card.png">',
        '<meta property="og:image:width" content="1200">',
        '<meta property="og:image:height" content="630">',
        f'<meta property="og:image:alt" content="{NAME} — Berkeley\'s housing pipeline, from the city\'s own records">',
        '<meta name="twitter:card" content="summary_large_image">',
        f'<meta name="twitter:title" content="{t}">',
        f'<meta name="twitter:description" content="{desc}">',
        f'<meta name="twitter:image" content="{SITE}/og-card.png">',
        END, ""])


def main():
    (DOCS / "favicon.svg").write_text(FAVICON, encoding="utf-8")
    print(f"wrote docs/favicon.svg")
    try:
        og_card(DOCS / "og-card.png")
        print(f"wrote docs/og-card.png ({(DOCS/'og-card.png').stat().st_size:,} bytes)")
        touch_icon(DOCS / "apple-touch-icon.png")
        print("wrote docs/apple-touch-icon.png (180x180)")
    except ImportError:
        sys.exit("Pillow is needed for the card: .venv/bin/pip install Pillow")

    n = 0
    for f in sorted(DOCS.glob("*.html")):
        h = f.read_text(encoding="utf-8")
        new = block(f.name)
        if BEGIN in h:
            h = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", new, h, flags=re.S)
        elif "</head>" in h:
            h = h.replace("</head>", new + "</head>", 1)
        else:
            print(f"  SKIP {f.name} — no </head>")
            continue
        f.write_text(h, encoding="utf-8")
        n += 1
    print(f"metadata written into {n} page(s)")


if __name__ == "__main__":
    main()
